imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     127.0.0.1
        port:     3306
        dbname:   Glit_test
        user:     root
        password:
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true