security:
    encoders:
        Glit\UserBundle\Entity\User: sha512

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
            main:
                entity: { class: Glit\UserBundle\Entity\User, property: uniqueName }

    #acl:
    #    connection: default

    firewalls:

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /user/security/login_check
                login_path: /user/security/login
            logout:
                path:   /user/security/logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/_wdt/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/img/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/security/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
